#!/bin/sh
set -u
set -e

cd /tmp/artifacts
tar xzf oshinko-rest-server_v0.2.2_linux_amd64.tar.gz
rm oshinko-rest-server_v0.2.2_linux_amd64.tar.gz
mv oshinko-rest-server_linux_amd64 /rest
chmod a+rwX /rest
